In [3]:
import pandas as pd
import numpy as np

In [4]:
df_metrics = pd.read_csv('_thiago_main_metrics.csv')

C:\Users\05646078199\AppData\Local\Temp\ipykernel_30912\2501031413.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df_metrics = pd.read_csv('_thiago_main_metrics.csv')

In [5]:
df = pd.read_csv('Corpus_Final_Resumos_Científicos.csv')

In [6]:
df_metrics.head()

,id_texto,adjective_ratio,adverbs,content_words,flesch,function_words,sentences_per_paragraph,syllables_per_content_word,words_per_sentence,noun_ratio,...,relative_pronouns_ratio,relative_pronouns_diversity_ratio,subjunctive_future_ratio,subjunctive_imperfect_ratio,subjunctive_present_ratio,subordinate_clauses,temporal_adjunct_ratio,adverbs_before_main_verb_ratio,verbal_time_moods_diversity,ratio_function_to_content_words
0,10058,0.07576,0.00000,0.60606,21.14455,0.39394,4.0,3.00000,33.00,0.42424,...,0.33333,0.5,0.0,0.0,0.00000,0.42857,0.28571,0.00000,2.0,0.65000
1,10253,0.07407,0.00926,0.57407,-6.52000,0.42593,4.0,3.72581,27.00,0.35185,...,0.00000,0.0,0.0,0.0,0.16667,0.66667,0.16667,0.16667,2.0,0.74194
2,10254,0.088,0.02400,0.61600,10.94480,0.38400,5.0,3.25974,25.00,0.36000,...,0.00000,0.0,0.0,0.0,0.00000,0.50000,0.16667,0.25000,1.0,0.62338
3,10255,0.06957,0.01739,0.57391,7.78592,0.42609,4.0,3.42424,28.75,0.36522,...,0.16667,1.0,0.0,0.0,0.00000,0.72727,0.00000,0.27273,1.0,0.74242
4,10258,0.05833,0.02500,0.63333,-8.88000,0.36667,5.0,3.63158,24.00,0.42500,...,0.00000,0.0,0.0,0.0,0.00000,0.53333,0.00000,0.06667,4.0,0.57895

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6618 entries, 0 to 6617
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Index     6618 non-null   int64
 1   Class     6618 non-null   object
 2   Abstract  6618 non-null   object
dtypes: int64(1), object(2)
memory usage: 155.2+ KB

In [8]:
df_main = pd.merge(df, df_metrics,  left_on='Index', right_on='id_texto', how='inner')

In [9]:
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6618 entries, 0 to 6617
Columns: 204 entries, Index to ratio_function_to_content_words
dtypes: float64(199), int64(2), object(3)
memory usage: 10.3+ MB

In [10]:
df_main.head()

,Index,Class,Abstract,id_texto,adjective_ratio,adverbs,content_words,flesch,function_words,sentences_per_paragraph,...,relative_pronouns_ratio,relative_pronouns_diversity_ratio,subjunctive_future_ratio,subjunctive_imperfect_ratio,subjunctive_present_ratio,subordinate_clauses,temporal_adjunct_ratio,adverbs_before_main_verb_ratio,verbal_time_moods_diversity,ratio_function_to_content_words
0,9524,Humana,Este artigo apresenta a ferramenta de autoria ...,9524,0.05882,0.01471,0.60294,17.59176,0.39706,4.0,...,0.00000,0.0,0.0,0.0,0.0,0.37500,0.00000,0.12500,1.0,0.65854
1,23303,Humana,"Recentemente, nota-se um grande crescimento da...",23303,0.07471,0.02299,0.54598,7.84748,0.45402,5.0,...,0.50000,0.5,0.0,0.0,0.0,0.81818,0.13333,0.18182,1.0,0.83158
2,24458,Humana,O advento da TV Digital tem contribuído para o...,24458,0.06122,0.02041,0.56122,11.39814,0.43878,5.0,...,0.33333,1.0,0.0,0.0,0.0,0.40000,0.00000,0.40000,2.0,0.78182
3,23313,Humana,Este artigo descreve o uso de personas em inte...,23313,0.10204,0.04082,0.57143,20.23689,0.42857,4.0,...,0.33333,1.0,0.0,0.0,0.0,0.40000,0.00000,0.20000,1.0,0.75000
4,23320,Humana,Em diversas operações relacionadas ao gerencia...,23320,0.0365,0.00730,0.60584,28.67085,0.39416,6.0,...,0.40000,1.0,0.0,0.0,0.0,0.58824,0.06667,0.17647,1.0,0.65060

### Análise Linguística das Métricas por Classe

- Análisar as métricas de cada classe onde os valores mais se aproximam
- Identificar quais são as métricas de cada classe que melhor distinguem as categorias de texto

#### Ajuste na Métrica _Adjetive_ratio

In [11]:
df_main[' adjective_ratio'] = pd.to_numeric(
    df_main[' adjective_ratio'],
    errors='coerce'
)

In [12]:
df_main = df_main.dropna()

In [13]:
df_main.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6582 entries, 0 to 6617
Columns: 204 entries, Index to ratio_function_to_content_words
dtypes: float64(200), int64(2), object(2)
memory usage: 10.3+ MB

In [14]:
df_main.head()

,Index,Class,Abstract,id_texto,adjective_ratio,adverbs,content_words,flesch,function_words,sentences_per_paragraph,...,relative_pronouns_ratio,relative_pronouns_diversity_ratio,subjunctive_future_ratio,subjunctive_imperfect_ratio,subjunctive_present_ratio,subordinate_clauses,temporal_adjunct_ratio,adverbs_before_main_verb_ratio,verbal_time_moods_diversity,ratio_function_to_content_words
0,9524,Humana,Este artigo apresenta a ferramenta de autoria ...,9524,0.05882,0.01471,0.60294,17.59176,0.39706,4.0,...,0.00000,0.0,0.0,0.0,0.0,0.37500,0.00000,0.12500,1.0,0.65854
1,23303,Humana,"Recentemente, nota-se um grande crescimento da...",23303,0.07471,0.02299,0.54598,7.84748,0.45402,5.0,...,0.50000,0.5,0.0,0.0,0.0,0.81818,0.13333,0.18182,1.0,0.83158
2,24458,Humana,O advento da TV Digital tem contribuído para o...,24458,0.06122,0.02041,0.56122,11.39814,0.43878,5.0,...,0.33333,1.0,0.0,0.0,0.0,0.40000,0.00000,0.40000,2.0,0.78182
3,23313,Humana,Este artigo descreve o uso de personas em inte...,23313,0.10204,0.04082,0.57143,20.23689,0.42857,4.0,...,0.33333,1.0,0.0,0.0,0.0,0.40000,0.00000,0.20000,1.0,0.75000
4,23320,Humana,Em diversas operações relacionadas ao gerencia...,23320,0.03650,0.00730,0.60584,28.67085,0.39416,6.0,...,0.40000,1.0,0.0,0.0,0.0,0.58824,0.06667,0.17647,1.0,0.65060

In [15]:
df_main.to_csv('df_main.csv', index=False)

In [72]:
# Cálculo da Média, Mediana, Desvio Padrão e Coeficiente de Variação de Cada Métrica para cada classe

df_main_human_text = df_main[df_main['Class'] == 'Humana'].dropna() 
df_main_polished_ai_text = df_main[df_main['Class'] == 'Polida_IA'].dropna()
df_main_generated_ai_text = df_main[df_main['Class'] == 'Gerada'].dropna()

In [73]:
print("N Humana:", len(df_main_human_text))
print("N Polida:", len(df_main_polished_ai_text))
print("N Gerada:", len(df_main_generated_ai_text))

N Humana: 2195
N Polida: 2195
N Gerada: 2192

#### Kruskal-Wallis + Dunn Pós-Hoc

In [89]:
from scipy.stats import kruskal

# Aplicar para a Métrica _Adjective_Ratio

metrica = "flesch"

H, p = kruskal(
    df_main_human_text[metrica],
    df_main_polished_ai_text[metrica],
    df_main_generated_ai_text[metrica]
)

In [90]:
print(f"H = {H}")
print(f"p = {p}")

H = 436.10002279614014
p = 2.0048563982322547e-95

In [91]:
print("Humana:", df_main_human_text[metrica].median())
print("Polida:", df_main_polished_ai_text[metrica].median())
print("Gerada:", df_main_generated_ai_text[metrica].median())

Humana: 11.23015
Polida: 6.54429
Gerada: 2.189305

In [92]:
print("Humana:", df_main_human_text[metrica].mean())
print("Polida:", df_main_polished_ai_text[metrica].mean())
print("Gerada:", df_main_generated_ai_text[metrica].mean())

Humana: 10.18386318906606
Polida: 6.845060765375854
Gerada: 1.8606915282846714

In [93]:
N = len(df_main_human_text) + len(df_main_polished_ai_text) + len(df_main_generated_ai_text)
k = 3

epsilon_squared = (H - k + 1) / (N - k)

print(epsilon_squared)

0.06598267560360847

In [ ]:
posthoc = sp.posthoc_dunn(
    [
        df_main_human_text[metrica],
        df_main_polished_ai_text[metrica],
        df_main_generated_ai_text[metrica]
    ],
    p_adjust="bonferroni"
)

posthoc.index = ["Humana", "Polida", "Gerada"]
posthoc.columns = ["Humana", "Polida", "Gerada"]

print(posthoc)

In [ ]:
medianas = {
    "Humana": median_h,
    "Polida": median_p,
    "Gerada": median_g
}

classe_dominante = max(medianas, key=medianas.get)

print(f"\nClasse com maior mediana: {classe_dominante}")

In [ ]:
if classe_dominante == "Gerada":

    p_h = posthoc.loc["Gerada", "Humana"]
    p_p = posthoc.loc["Gerada", "Polida"]

    if p_h < 0.05 and p_p < 0.05:
        print(
            f"A métrica '{metrica}' caracteriza a classe Gerada "
            f"(difere significativamente de Humana e Polida)."
        )
    else:
        print(
            f"A classe Gerada possui a maior mediana, "
            f"mas não difere significativamente de todas as demais."
        )

#### Segmentação do Dataframe por Classe

In [49]:
# Classe Humana

def calculate_metrics(df, class_name, start_col=4):

    metric_cols = df.columns[start_col:]

    df[metric_cols] = df[metric_cols].apply(
        pd.to_numeric,
        errors='coerce'
    )

    metrics = []

    for column in metric_cols:

        media = df[column].mean()
        mediana = df[column].median()
        desvio_padrao = df[column].std()

        cv = (
            (desvio_padrao / media) * 100
            if media != 0 and not np.isnan(media)
            else np.nan
        )

        metrics.append({
            'Classe': class_name,
            'Métrica': column,
            'Média': media,
            'Mediana': mediana,
            'Desvio Padrão': desvio_padrao,
            'Coeficiente de Variação (%)': cv
        })

    return pd.DataFrame(metrics)

In [50]:
df_human_metrics = calculate_metrics(df_main_human_text, 'Humana')
df_human_metrics.to_csv('human_metrics.csv', index=False)

df_polished_metrics = calculate_metrics(df_main_polished_ai_text, 'Polida_IA')
df_polished_metrics.to_csv('polished_metrics.csv', index=False)

df_generated_metrics = calculate_metrics(df_main_generated_ai_text, 'Gerada')
df_generated_metrics.to_csv('generated_metrics.csv', index=False)

C:\Users\Thiago Lobo\AppData\Local\Temp\ipykernel_5196\2117512793.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[metric_cols] = df[metric_cols].apply(
C:\Users\Thiago Lobo\AppData\Local\Temp\ipykernel_5196\2117512793.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[metric_cols] = df[metric_cols].apply(
C:\Users\Thiago Lobo\AppData\Local\Temp\ipykernel_5196\2117512793.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[metric_cols] = df[metric_cols].apply(

In [51]:
df_human_metrics.head()

,Classe,Métrica,Média,Mediana,Desvio Padrão,Coeficiente de Variação (%)
0,Humana,adjective_ratio,1.776978,0.07000,25.264578,1421.772115
1,Humana,adverbs,0.018252,0.01562,0.016326,89.448933
2,Humana,content_words,0.590845,0.59000,0.035084,5.937861
3,Humana,flesch,10.183863,11.23015,14.472748,142.114519
4,Humana,function_words,0.409155,0.41000,0.035084,8.574627

In [52]:
df_polished_metrics.head()

,Classe,Métrica,Média,Mediana,Desvio Padrão,Coeficiente de Variação (%)
0,Polida_IA,adjective_ratio,1.607802,0.07115,23.978920,1491.410322
1,Polida_IA,adverbs,0.018701,0.01695,0.015712,84.016239
2,Polida_IA,content_words,0.585650,0.58475,0.032162,5.491596
3,Polida_IA,flesch,6.845061,6.54429,11.741258,171.528909
4,Polida_IA,function_words,0.414350,0.41525,0.032162,7.761913

In [53]:
df_generated_metrics.head()

,Classe,Métrica,Média,Mediana,Desvio Padrão,Coeficiente de Variação (%)
0,Gerada,adjective_ratio,1.790593,0.081970,25.280948,1411.875873
1,Gerada,adverbs,0.015139,0.015620,0.013032,86.086246
2,Gerada,content_words,0.604823,0.603310,0.028678,4.741543
3,Gerada,flesch,1.860692,2.189305,13.268180,713.077903
4,Gerada,function_words,0.395177,0.396690,0.028678,7.256990

In [54]:
df_all_metrics = pd.concat(
    [
        df_human_metrics,
        df_polished_metrics,
        df_generated_metrics
    ],
    ignore_index=True
)

In [56]:
df_compare = (
    df_all_metrics
    .pivot(
        index='Métrica',
        columns='Classe',
        values='Média'
    )
)

df_compare.head(50)

Classe,Gerada,Humana,Polida_IA
Métrica,,,
adjective_ratio,1.790593,1.776978,1.607802
abstract_nouns_ratio,0.085378,0.068153,0.076430
add_neg_conn_ratio,0.001937,0.002643,0.002751
add_pos_conn_ratio,0.053529,0.041166,0.045088
adj_arg_ovl,0.884256,1.679681,1.088869
adj_cw_ovl,1.017015,1.870824,1.181416
adj_stem_ovl,1.316364,2.390180,1.488858
adjacent_refs,0.026779,0.096816,0.056580
adjective_diversity_ratio,0.937997,0.922219,0.929586
adjectives_ambiguity,2.265354,2.654260,2.380020
adjectives_max,0.152796,0.132090,0.135911
adjectives_min,0.026448,0.024030,0.022161
adjectives_standard_deviation,0.046731,0.041114,0.042660
adjunct_per_clause,0.822618,0.743778,0.809124
adverbs,0.015139,0.018252,0.018701
adverbs_ambiguity,1.948004,1.936963,2.298529
adverbs_before_main_verb_ratio,0.142839,0.182721,0.216866
adverbs_diversity_ratio,0.763691,0.733520,0.786364
adverbs_max,0.044245,0.048870,0.053241
adverbs_min,0.000125,0.000696,0.000199
adverbs_standard_deviation,0.017983,0.019556,0.021677
anaphoric_refs,0.053756,0.190525,0.110655
and_ratio,0.042074,0.028576,0.029572
apposition_per_clause,0.030461,0.044985,0.043630
arg_ovl,0.967757,1.574178,1.144230
aux_plus_PCP_per_sentence,0.172134,0.297706,0.205680
brunet,10.006110,9.921792,9.899916
cau_neg_conn_ratio,0.001742,0.000959,0.001742
cau_pos_conn_ratio,0.036804,0.044843,0.044143
clauses_per_sentence,2.726447,3.001080,2.778921
concretude_1_25_ratio,0.006610,0.003385,0.004996
concretude_25_4_ratio,0.613722,0.612327,0.627232
concretude_4_55_ratio,0.355135,0.360401,0.345370
concretude_55_7_ratio,0.024483,0.023875,0.022376
concretude_mean,3.885960,3.903387,3.867604
concretude_std,0.662293,0.658728,0.653750
conn_ratio,0.090096,0.084418,0.086146
content_density,1.544303,1.462813,1.428579
content_word_diversity,0.882364,0.850295,0.874223
content_word_max,0.607539,0.600266,0.590515
content_word_min,0.487375,0.482009,0.467644
content_word_standard_deviation,0.043899,0.044246,0.045449
content_words,0.604823,0.590845,0.585650
content_words_ambiguity,3.788842,4.244251,4.042902
coordinate_conjunctions_per_clauses,0.442380,0.288965,0.305979
coreference_pronoun_ratio,0.007611,0.044028,0.021257
cross_entropy,0.508411,0.496112,0.478454
cw_freq,355998.744516,480037.803750,389272.274449
cw_freq_bra,4.497483,4.616720,4.635027
cw_freq_brwac,4.128433,4.260593,4.281625