In [ ]:
import pandas as pd
import numpy as np
import statistics

In [ ]:
df = pd.read_csv('metadados_completos_sol_sbc_portugues_2020_2025 - Métricas Linguísticas.csv')

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10066 entries, 0 to 10065
Data columns (total 87 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Id                               10066 non-null  int64
 1   Title                            10066 non-null  object
 2   Category                         10066 non-null  object
 3   URL_Title                        10066 non-null  object
 4   Authors                          10066 non-null  object
 5   Event                            10066 non-null  object
 6   Date                             10066 non-null  object
 7   Box                              10066 non-null  object
 8   Abstract                         10066 non-null  object
 9   Keywords                         10066 non-null  object
 10  Publisher                        10066 non-null  object
 11  URL_Paper                        10066 non-null  object
 12  Abstract_Language                10066 non-null  object
 13  Title_Language                   10066 non-null  object
 14  Year                             10066 non-null  int64
 15  adjective_ratio                  10057 non-null  float64
 16  adverbs                          10057 non-null  float64
 17  content_words                    10057 non-null  float64
 18  flesch                           10057 non-null  float64
 19  function_words                   10057 non-null  float64
 20  sentences_per_paragraph          10057 non-null  float64
 21  syllables_per_content_word       10057 non-null  float64
 22  words_per_sentence               10057 non-null  float64
 23  noun_ratio                       10057 non-null  float64
 24  paragraphs                       10057 non-null  float64
 25  sentences                        10057 non-null  float64
 26  words                            10057 non-null  float64
 27  pronoun_ratio                    10057 non-null  float64
 28  verbs                            10057 non-null  float64
 29  logic_operators                  10057 non-null  float64
 30  and_ratio                        10057 non-null  float64
 31  if_ratio                         10057 non-null  float64
 32  or_ratio                         10057 non-null  float64
 33  negation_ratio                   10057 non-null  float64
 34  cw_freq                          10057 non-null  float64
 35  cw_freq_brwac                    10057 non-null  float64
 36  cw_freq_bra                      10057 non-null  float64
 37  min_cw_freq                      10057 non-null  float64
 38  min_cw_freq_brwac                10057 non-null  float64
 39  min_freq_brwac                   10057 non-null  float64
 40  min_cw_freq_bra                  10057 non-null  float64
 41  min_freq_bra                     10057 non-null  float64
 42  freq_brwac                       10057 non-null  float64
 43  freq_bra                         10057 non-null  float64
 44  hypernyms_verbs                  10057 non-null  float64
 45  brunet                           10057 non-null  float64
 46  honore                           10057 non-null  float64
 47  personal_pronouns                10057 non-null  float64
 48  ttr                              10057 non-null  float64
 49  conn_ratio                       10057 non-null  float64
 50  add_neg_conn_ratio               10057 non-null  float64
 51  add_pos_conn_ratio               10057 non-null  float64
 52  cau_neg_conn_ratio               10057 non-null  float64
 53  cau_pos_conn_ratio               10057 non-null  float64
 54  log_neg_conn_ratio               10057 non-null  float64
 55  log_pos_conn_ratio               10057 non-null  float64
 56  tmp_neg_conn_ratio               10057 non-null  float64
 57  tmp_pos_conn_ratio               10057 non-null  float64
 58  adjectives_ambiguity             10057 non-null  float64
 59  adverbs_ambiguity                10057 non-null  float64
 60  nouns_ambiguity                  10057 non-null  float64
 61  verbs_ambiguity                  10057 non-null  float64
 62  yngve                            10057 non-null  float64
 63  frazier                          10057 non-null  float64
 64  dep_distance                     10057 non-null  float64
 65  cross_entropy                    10057 non-null  float64
 66  content_density                  10057 non-null  float64
 67  adjacent_refs                    10057 non-null  float64
 68  anaphoric_refs                   10057 non-null  float64
 69  adj_arg_ovl                      10057 non-null  float64
 70  arg_ovl                          10057 non-null  float64
 71  adj_stem_ovl                     10057 non-null  float64
 72  stem_ovl                         10057 non-null  float64
 73  adj_cw_ovl                       10057 non-null  float64
 74  lsa_adj_mean                     10057 non-null  float64
 75  lsa_adj_std                      10057 non-null  float64
 76  lsa_all_mean                     10057 non-null  float64
 77  lsa_all_std                      10057 non-null  float64
 78  lsa_paragraph_mean               10057 non-null  float64
 79  lsa_paragraph_std                10057 non-null  float64
 80  lsa_givenness_mean               10057 non-null  float64
 81  lsa_givenness_std                10057 non-null  float64
 82  lsa_span_mean                    10057 non-null  float64
 83  lsa_span_std                     10057 non-null  float64
 84  negative_words                   10057 non-null  float64
 85  positive_words                   10057 non-null  float64
 86  ratio_function_to_content_words  10057 non-null  float64
dtypes: float64(72), int64(2), object(13)
memory usage: 6.7+ MB

In [3]:
df.head()

,Id,Title,Category,URL_Title,Authors,Event,Date,Box,Abstract,Keywords,...,lsa_all_std,lsa_paragraph_mean,lsa_paragraph_std,lsa_givenness_mean,lsa_givenness_std,lsa_span_mean,lsa_span_std,negative_words,positive_words,ratio_function_to_content_words
0,0,The Role of Social Image as a Behavior Filter:...,ANAIS DE EVENTO,https://sol.sbc.org.br/index.php/wesaac/articl...,"Baqueta, Jeferson J.; Morveli-Espinoza, Mariel...",ANAIS DO WORKSHOP-ESCOLA DE SISTEMAS DE AGENTE...,2020-07-07,Caixa 1,"Nos sistemas multi-agente (SMA), os modelos de...",['No keywords available'],...,0.03733,0.0,0.0,0.92420,0.03869,0.92629,0.03755,0.46465,0.52525,0.68687
1,1,Symbolic Environments of Agent Societies,ANAIS DE EVENTO,https://sol.sbc.org.br/index.php/wesaac/articl...,"Costa, Antônio Carlos da Rocha",ANAIS DO WORKSHOP-ESCOLA DE SISTEMAS DE AGENTE...,2020-07-07,Caixa 1,Este artigo analisa o conceito de ambiente sim...,['No keywords available'],...,0.04131,0.0,0.0,0.88686,0.03489,0.88699,0.03502,0.21277,0.29787,0.53191
2,2,Emergency Remote Computer Science Education in...,PERIÓDICOS,https://journals-sol.sbc.org.br/index.php/rbie...,; ; ;,REVISTA BRASILEIRA DE INFORMáTICA NA EDUCAçãO,2020-12-14,Caixa 1,"No final do ano de 2019, ocorreu o surto de um...","['Emergency Remote Education', 'Computer Scien...",...,0.04237,0.0,0.0,0.89760,0.03615,0.90849,0.04138,0.26016,0.35772,0.71545
3,3,Neural Network for Self-Checkout Fraud Detection,ANAIS DE EVENTO,https://sol.sbc.org.br/index.php/eramiasp/arti...,"Velloso, Haline; Dias, Maurício",PROCEEDINGS OF THE REGIONAL SCHOOL OF ARTIFICI...,2020-08-19,Caixa 2,Pessoas que utilizam o serviço de self-checkou...,['No keywords available'],...,0.09366,0.0,0.0,0.84621,0.06932,0.86483,0.04845,0.25676,0.41892,0.60811
4,4,Abertura do XXXIII Brazilian Symposium on Soft...,ANAIS DE EVENTO,https://sol.sbc.org.br/index.php/sbes_estendid...,"Gerosa, Marco Aurélio; Prikladnicki, Rafael",COMPANION PROCEEDINGS OF THE BRAZILIAN SYMPOSI...,2020-01-21,Caixa 2,Mensagem dos chairs e abertura do evento,['No keywords available'],...,0.00000,0.0,0.0,0.00000,0.00000,0.00000,0.00000,0.50000,0.25000,0.75000

Medidas Estatísticas Descritivas

In [20]:
list_metrics = df.columns.tolist()[15:]

df_mean = pd.DataFrame(columns=['Métrica', 'Ano', 'Média', 'Mediana', 'Desvio Padrão'])

for metric in list_metrics:
    for year in range(2020, 2026):
        subset = df[df['Year'] == year]
        mean_value = subset[metric].mean()
        median_value = statistics.median(subset[metric].dropna())
        std_value = subset[metric].std()
        df_mean = pd.concat([
            df_mean,
            pd.DataFrame({
                'Métrica': [metric],
                'Ano': [year],
                'Média': [mean_value],
                'Mediana': [median_value],
                'Desvio Padrão': [std_value]  
            })
        ], ignore_index=True)

df_mean.head()

C:\Users\Thiago Lobo\AppData\Local\Temp\ipykernel_11340\3027538048.py:11: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_mean = pd.concat([

           Métrica   Ano     Média  Mediana  Desvio Padrão
0  adjective_ratio  2020  0.072000  0.07080       0.029075
1  adjective_ratio  2021  0.074785  0.07258       0.030715
2  adjective_ratio  2022  0.071944  0.07003       0.030017
3  adjective_ratio  2023  0.073003  0.07143       0.029486
4  adjective_ratio  2024  0.073316  0.07207       0.033841

Desvio Padrão das Métricas